name: workflow.yml
on:
  push:
    branches:
      - main

env:
  JAVA_VERSION: '17'
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2

jobs:
  test:
    runs-on: windows

    steps:
      - name: Checkout repository test
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run all tests
        run: ./gradlew clean test
